# The URL the site will be built for
base_url = "https://rutrum.net"

title = "Rutrum"
description = "Personal website."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
  { name = "tags", feed = true }
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# Put all your custom variables here

# footer.links = [ "A", "B", "C" ]

[[extra.footer.links]]
text = "TypeSync"
url = "https://typesync.rutrum.net"
icon = "nf-fa-keyboard_o"

[[extra.footer.links]]
text = "GitHub"
url = "https://github.com/rutrum"
icon = "nf-fa-github"

[[extra.footer.links]]
text = "stringcase.org"
url = "https://stringcase.org"
icon = "nf-fa-quote_right"
