base_url = "https://rutrum.net"
title = "rutrum"
description = "Personal website."
compile_sass = true
theme = "typeset"
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
  { name = "tags", feed = true }
]

[markdown.highlighting]
light_theme = "catppuccin-latte"
dark_theme = "catppuccin-frappe"

[extra]
author = "rutrum"

nav_links = [
    { name = "Blog", url = "/blog" },
    { name = "About", url = "/about" },
]

[[extra.footer_links]]
text = "GitHub"
url = "https://github.com/rutrum"
icon = "github"

[[extra.footer_links]]
text = "stringcase.org"
url = "https://stringcase.org"
icon = "quote"
